# Generated by Django 5.2.5 on 2025-08-06 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('adresse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_affaire', models.CharField(max_length=50, unique=True)),
                ('nom_chantier', models.CharField(max_length=255)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('commentaires', models.TextField(blank=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suivi_essais.client')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi_essais.etat')),
            ],
        ),
        migrations.CreateModel(
            name='Essai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_essai', models.CharField(choices=[('CAROTTE', 'Carottage'), ('SONDAGE', 'Sondage'), ('PERMEA', 'Perméabilité')], max_length=20)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('fichier_rapport', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essais', to='suivi_essais.affaire')),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suivi_essais.etat')),
            ],
        ),
        migrations.CreateModel(
            name='LogEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_log', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('essai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi_essais.essai')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi_essais.etat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
