# Generated by Django 5.2.5 on 2025-08-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_essais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='affaire',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affaire',
            name='numero_os',
            field=models.CharField(blank=True, max_length=100, verbose_name="Numéro d'ordre de service"),
        ),
        migrations.AddField(
            model_name='essai',
            name='nom',
            field=models.CharField(default='NOUVEL_ESSAI', help_text='Ex: 2025_ACHENHEIM_CHARMES_C01', max_length=100),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='code_affaire',
            field=models.CharField(help_text='Ex: 2542/001', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='nom_chantier',
            field=models.CharField(help_text='Nom ou lieu du chantier', max_length=255),
        ),
    ]
