# Generated by Django 5.2.5 on 2025-08-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_essais', '0002_affaire_adresse_affaire_date_limite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profondeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diametre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nature_enrobe', models.CharField(blank=True, max_length=100)),
                ('epaisseur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observations', models.TextField(blank=True)),
                ('essai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suivi_essais.essai')),
            ],
        ),
        migrations.CreateModel(
            name='Permeabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profondeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duree_mesure', models.IntegerField(blank=True, help_text='Durée en secondes', null=True)),
                ('perm_k', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Coefficient k (m/s)')),
                ('observations', models.TextField(blank=True)),
                ('essai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suivi_essais.essai')),
            ],
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profondeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('methode', models.CharField(blank=True, max_length=100)),
                ('resistance_sol', models.CharField(blank=True, max_length=100)),
                ('humidite', models.CharField(blank=True, max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('essai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suivi_essais.essai')),
            ],
        ),
    ]
