# Generated by Django 5.2.5 on 2025-08-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_essais', '0003_carottage_permeabilite_sondage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos_affaires/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='suivi_essais.affaire')),
            ],
        ),
    ]
