# Generated by Django 5.2.5 on 2025-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_essais', '0004_photoaffaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carottage',
            name='diametre',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Diamètre en cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='carottage',
            name='epaisseur',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Épaisseur en cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='carottage',
            name='profondeur',
            field=models.DecimalField(decimal_places=1, help_text='Profondeur en cm', max_digits=5),
        ),
    ]
