# Generated by Django 5.2.5 on 2025-08-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_essais', '0005_alter_carottage_diametre_alter_carottage_epaisseur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essai',
            name='fichier_rapport',
        ),
        migrations.RemoveField(
            model_name='essai',
            name='nom',
        ),
        migrations.AddField(
            model_name='essai',
            name='campagne_code_chantier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='cc48_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='cc48_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='cc48_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='commentaire_saisie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='coord_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='coord_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='date_enlevement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='date_etiquette',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='date_formulaire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='date_leve',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='date_limite_realisation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='date_programmation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='date_rendu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='identifiant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='libelle',
            field=models.CharField(default='Sans libelle', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essai',
            name='os_libelle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='os_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='os_no_engagement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='prevoir_enlev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='essai',
            name='rue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='essai',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='essai',
            name='etat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suivi_essais.etat'),
        ),
    ]
