# Generated by Django 5.2.5 on 2025-08-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_essais', '0006_remove_essai_fichier_rapport_remove_essai_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essai',
            name='identifiant',
            field=models.CharField(default='VIDE', max_length=50),
            preserve_default=False,
        ),
    ]
