# Generated by Django 5.2.5 on 2025-08-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_essais', '0007_alter_essai_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essai',
            name='identifiant',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
