# Generated by Django 5.2.5 on 2025-08-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_essais', '0008_alter_essai_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essai',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default='1976-06-12'),
            preserve_default=False,
        ),
    ]
